### PR TITLE
Auto optimizations

### PR DESCRIPTION
**Pull request by evenicoulddoit**
TODOS:

- [x] Rebase / rationalise
- [x] Add settings to default optimize on/off
- [x] Document

### CODE REVIEW

**Comment by evenicoulddoit** [comment]
Fixes #6 as an aside

**Comment by evenicoulddoit** [comment]
@gareth-lloyd would love your input on this if you can spare the time? :)

**Comment by gareth-lloyd** [comment]
I read through this today. I like the approach! I'll try to find time for a line-by-line review and then I'd be happy to start using it on some of our views ASAP.

**Comment by jojolalpin** [comment]
Hi,
Anything I can do to help merge the auto optimization ?
CI only fails for django 1.8 and DRF 3.6, but DRF is now at 3.7.7 and oldest supported version of Django is 1.10.

**Comment by KyeRussell** [comment]
As discussed elsewhere, Django 1.8 support should not be dropped as per Django’s support schedule.

**Comment by evenicoulddoit** [comment]
@jojolalpin @KyeRussell the *tests pass* now on this branch, and master has been merged into it, so it conforms to the current Django support lifecycles as well as Rest framework current - 2. The only thing preventing it from being merged is lack of feedback. I could just merge it as-is, as it shouldn't negatively affect users unless they turn the feature on. Happy to take suggestions!

**Comment by jojolalpin** [comment]
Hi,

Yesterday I managed to pass some tests on my fork but was struggling with
the set thing for Django 2.
I will make tries with the updated branch as I have a project with a set of
interlinked serializers that should show the gains in perf (as for now it
takes 30 secs to run a query...)
I will let you know asap the results and any problems I encounter.

**Comment by jojolalpin** [comment]
Hi, any idea when you merge this ?

**Comment by evenicoulddoit** [comment]
Hey @jojolalpin. Sorry, I'm no longer working with DRF so I've not had the ability to run this in the wild. What's your experience been with it? Happy to build a very though I think, because IIRC I've turned the feature off by default?

**Comment by jojolalpin** [comment]
Hi Ian,

I pull from the commit with this option. Everything works well and I think
you should merge what is ok if you do not work on it anymore.
Your extension comes in my default setting with drf.

Thanks a lot for it.

Julien

**Comment by jojolalpin** [comment]
Thanks a lot!

**Comment by evenicoulddoit** [comment]
@jojolalpin now available in `0.6.0` - thanks for the extreme patience!

**Comment by jojolalpin** [comment]
Just a quick question, permissions are still not checked when you expand?

**Comment by evenicoulddoit** [comment]
I think that's correct, but this was all done so long ago! Would need to sit down properly to give you a more complete answer

**Comment by jojolalpin** [comment]
If you did not add this "recently", permissions are not checked. I had to
make a filter working with a not so old commit.

**Comment by evenicoulddoit** [comment]
Happy to take contributions if you've worked on something?

**Comment by jojolalpin** [comment]
No it was very specific for a rarely called query and very basic. Could
have done more beautiful but I was lazy.

**Comment by jojolalpin** [comment]
to end about permissions, having each object read permissions (I use
dry-rest-permissions <https://github.com/dbkaplan/dry-rest-permissions>) in
the response allows to simply filter it.

**Pull request merged**
