### PR TITLE
Modification in case self.request is None (when using DRF js client)

### PR DESCRIPTION
**Pull request by jojolalpin**
Modification related to issue #9

### CODE REVIEW

**Comment by evenicoulddoit** [comment]
Does this make sense to go within the for loop? I suppose it means that you could define the extensions fields without a request, but in practical terms wouldn't it be easier to just put a:

```py
# Request is unset during API client discovery
if self.request is None:
    return context
```

at the top of the method? Happy either way, but I think I'll add a comment to remind myself why request could ever be `None`

**Comment by jojolalpin** [comment]
Sure, merge request updated.

**Comment by jojolalpin** [comment]
Hi Ian,
I am not a specialist of travis and codecov.
I do not know what to do. Give me an hint and I will do the changes.
note: First commit was Ok

**Comment by evenicoulddoit** [comment]
@jojolalpin - it's complaining because code coverage has noticed that the coverage has decreased. Although you weren't testing the logic previously, because it was on a line which was *already tested*, it assumed that it was. Now it's in it's own condition, it realises that the code isn't tested.

On the weekend I'm happy to write a basic test that asserts that the method returns an empty dict when `self.request is None`, a la:

```py
def test_returns_empty_dict_when_no_request(self):
    view = self.get_instance(view_class)
    view.format_kwarg = 'json'
    context = view.get_serializer_context()
    self.assertEqual(dict(), context)
```

**Pull request closed without merging**
